version: '3.8'

services:
  backend-prod:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: "${ECR_IMAGE}"
    container_name: "${SERVICE_NAME}-prod"
    ports:
      - "9000:8080"
    tty: true
    stdin_open: true

  backend-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: "${SERVICE_NAME}-dev:latest"
    container_name: "${SERVICE_NAME}-dev"
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"
